name: Gerador de Atividades Recentes

on:
  schedule:
    # Roda a cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Atualiza a lista de atividades no README
    steps:
      - uses: actions/checkout@v4
      - uses: actions/activity-generator@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Opcional: define o tipo de atividade a ser incluída. 
          # Deixe comentado para incluir todas as atividades abaixo.
          # ACTIVITY_TYPES: "PushEvent,CreateEvent"
